name: deploy-pipeline
on:
  workflow_dispatch:

jobs:
  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Print head git commit message
        run: |
          echo "$(git show -s --format=%s)" 
          
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo starting build


  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: "https://atlassian.com"
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy dev


  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: "https://atlassian.com"
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo deploy prd
